const airportCodes: Record<string, string> = {
  TRA: 'Trabzon',
  KLM: 'Amsterdam',
  TFL: 'London',
  DLM: 'Dalaman',
  BCN: 'Barcelona',
  OPO: 'Porto',
  PFO: 'Paphos',
  NCE: 'Nice',
  DAL: 'Dallas',
  LPA: 'Las Palmas',
  HER: 'Heraklion',
  MPH: 'Masbate',
  MIA: 'Miami',
  LIS: 'Lisbon',
  RHO: 'Rhodes',
  BRI: 'Bari',
  IBZ: 'Ibiza',
  MJT: 'Miðvágur',
  CND: 'Cundinamarca',
  CTA: 'Catania',
  GRO: 'Girona-Costa Brava Airport',
  TBS: 'Tbilisi',
  TFS: 'Tenerife South',
  ALC: 'Alicante',
  ATH: 'Athens',
  ADB: 'Izmir',
  RAK: 'Marrakesh',
  FAO: 'Faro',
  AOK: 'Karpathos',
  AGP: 'Malaga',
  SPC: 'La Palma',
  PDL: 'Ponta Delgada',
  DSS: 'Dakar',
  KGS: 'Kos',
  ZTH: 'Zakynthos',
  PMI: 'Palma de Mallorca',
  SPU: 'Split',
  KEF: 'Reykjavik',
};

const airlineCompanyCodes: Record<string, string> = {
  HV: 'Transavia',
  OR: 'Transavia',
  KL: 'KLM Royal Dutch Airlines',
  MP: 'Martinair',
  DL: 'Delta Air Lines',
  CD: 'Nauru Airlines ',
};

export { airportCodes, airlineCompanyCodes };
